### ISSUE TITLE
Dockerfile won't build: error during compilation

### ISSUE THREAD

**Issue by TomWis97** [gost/dashboard-v2#3]
When attempting to build the application, the Dockerfile fails.

**Steps to reproduce:**  
```bash
git clone https://github.com/gost/dashboard-v2
cd dashboard-v2
docker build .
```

**Result:**  
Please see [output.txt](https://github.com/gost/dashboard-v2/files/2586016/output.txt).

**Comment by bertt** [comment]
I can reproduce this, log output:

```
16:51:36] Starting 'polymer:cli'...
info: [cli.command.build]    Clearing build/ directory...


<link rel="import" href="entities-view-styles.html">
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~

file:///usr/src/app/public/elements/views/entities-view.html(17,25) error [could-not-load] - Unable to load import: Not found: "/usr/src/app/public/elements/views/entities-view-styles.html"


<link rel="import" href="sensor-view-styles.html" />
                        ~~~~~~~~~~~~~~~~~~~~~~~~~

file:///usr/src/app/public/elements/views/sensor-view.html(13,25) error [could-not-load] - Unable to load import: Not found: "/usr/src/app/public/elements/views/sensor-view-styles.html"


<link rel="import" href="observedproperty-view-styles.html" />
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

file:///usr/src/app/public/elements/views/observedproperty-view.html(13,25) error [could-not-load] - Unable to load import: Not found: "/usr/src/app/public/elements/views/observedproperty-view-styles.html"


<link rel="import" href="observation-view-styles.html" />
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

file:///usr/src/app/public/elements/views/observation-view.html(14,25) error [could-not-load] - Unable to load import: Not found: "/usr/src/app/public/elements/views/observation-view-styles.html"


<link rel="import" href="featureofinterest-view-styles.html" />
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

file:///usr/src/app/public/elements/views/featureofinterest-view.html(18,25) error [could-not-load] - Unable to load import: Not found: "/usr/src/app/public/elements/views/featureofinterest-view-styles.html"

error: [cli.main]   Promise rejection: Error: 5 error(s) occurred during build.
error: [cli.main]   Error: 5 error(s) occurred during build.
    at BuildAnalyzer._done (/usr/src/app/node_modules/polymer-cli/node_modules/polymer-build/lib/analyzer.js:275:36)
    at BuildAnalyzer.<anonymous> (/usr/src/app/node_modules/polymer-cli/node_modules/polymer-build/lib/analyzer.js:236:26)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/src/app/node_modules/polymer-cli/node_modules/polymer-build/lib/analyzer.js:17:58)
    at <anonymous>

[16:51:59] 'polymer:cli' errored after 23 s
[16:51:59] Error: Command failed: node ./node_modules/polymer-cli/bin/polymer.js build
error: [cli.main]   Promise rejection: Error: 5 error(s) occurred during build.
error: [cli.main]   Error: 5 error(s) occurred during build.
    at BuildAnalyzer._done (/usr/src/app/node_modules/polymer-cli/node_modules/polymer-build/lib/analyzer.js:275:36)
    at BuildAnalyzer.<anonymous> (/usr/src/app/node_modules/polymer-cli/node_modules/polymer-build/lib/analyzer.js:236:26)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/src/app/node_modules/polymer-cli/node_modules/polymer-build/lib/analyzer.js:17:58)
    at <anonymous>

    at ChildProcess.exithandler (child_process.js:272:12)
    at emitTwo (events.js:135:13)
    at ChildProcess.emit (events.js:224:7)
    at maybeClose (internal/child_process.js:943:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
[16:51:59] 'dist' errored after 24 s
[16:51:59] Error: Command failed: node ./node_modules/polymer-cli/bin/polymer.js build
error: [cli.main]   Promise rejection: Error: 5 error(s) occurred during build.
error: [cli.main]   Error: 5 error(s) occurred during build.
    at BuildAnalyzer._done (/usr/src/app/node_modules/polymer-cli/node_modules/polymer-build/lib/analyzer.js:275:36)
    at BuildAnalyzer.<anonymous> (/usr/src/app/node_modules/polymer-cli/node_modules/polymer-build/lib/analyzer.js:236:26)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/src/app/node_modules/polymer-cli/node_modules/polymer-build/lib/analyzer.js:17:58)
    at <anonymous>
    at ChildProcess.exithandler (child_process.js:272:12)
    at emitTwo (events.js:135:13)
    at ChildProcess.emit (events.js:224:7)
    at maybeClose (internal/child_process.js:943:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
The command '/bin/sh -c npm install -g bower && npm install && bower install --allow-root && npm install -g gulp && gulp dist' returned a non-zero code: 1
```
